# Generated by Django 5.1.4 on 2025-02-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='Icon',
        ),
        migrations.AlterField(
            model_name='service',
            name='img',
            field=models.ImageField(height_field=260, upload_to='Services/Images', verbose_name='Image', width_field=370),
        ),
    ]
