# Generated by Django 5.1.4 on 2025-02-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_service_icon_alter_service_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='img',
            field=models.ImageField(height_field='260', upload_to='Services/Images', verbose_name='Image', width_field='370'),
        ),
    ]
