# Generated by Django 5.1.4 on 2025-02-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_service_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='img',
            field=models.ImageField(upload_to='Services/Images', verbose_name='Image'),
        ),
    ]
