# Generated by Django 5.1.4 on 2025-03-03 09:50

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_service_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='img',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[370, 260], upload_to='Services/Images', verbose_name='Image'),
        ),
    ]
