# Generated by Django 5.1.4 on 2025-03-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_service_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(choices=[('icon-online-shopping', 'Shopping Icon'), ('icon-growth', 'Growth Icon'), ('icon-webpage', 'Webpage Icon'), ('icon-front-end', 'Frontend Icon'), ('icon-two-app-development', 'App Development Icon 2'), ('icon-two-planning', 'Planning Icon 2')], default='icon-growth', max_length=50, verbose_name='Icon'),
            preserve_default=False,
        ),
    ]
