# Generated by Django 5.1.4 on 2025-03-12 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_service_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='')),
                ('icon_class', models.CharField(max_length=50, verbose_name='')),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.icons', verbose_name='icon'),
        ),
    ]
