# Generated by Django 5.1.4 on 2025-03-12 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_icons_alter_service_icon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Icons',
            new_name='Icon',
        ),
    ]
