# Generated by Django 5.1.4 on 2025-03-12 01:31

import django_resized.forms
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_icons_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='icon_class',
            field=models.CharField(max_length=50, verbose_name='Icon Class'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Icon Name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='img',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[370, 260], upload_to=main.models.path_and_rename, verbose_name='Image'),
        ),
    ]
