# Generated by Django 5.1.4 on 2025-03-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_icon_icon_class_alter_icon_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='paragraph_1',
            field=models.TextField(default='Helllllllllllllllllllllllllllllllllllllllo', verbose_name='Main Paragragh'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='paragraph_2',
            field=models.TextField(default='Helllllllllllllllllllllllllllllo', verbose_name='Sub Paragragh'),
            preserve_default=False,
        ),
    ]
