# Generated by Django 5.1.4 on 2025-03-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='arabic_name',
            field=models.CharField(default='ش', max_length=50, verbose_name='Arabic Name'),
            preserve_default=False,
        ),
    ]
