# Generated by Django 5.1.4 on 2025-03-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_tag_arabic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='a', verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
