# Generated by Django 5.1.4 on 2025-03-19 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_tag_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
                ('thumb', models.ImageField(upload_to='projects/thumbnail/', verbose_name='Thumbnail')),
                ('img', models.ImageField(upload_to='projects/images/', verbose_name='Image')),
                ('excerpt', models.TextField(verbose_name='Excerpt')),
                ('client', models.CharField(max_length=50, verbose_name='Client')),
                ('date', models.DateField(verbose_name='Date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_tag', to='main.tag')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
