# Generated by Django 5.1.4 on 2025-04-01 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testmonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                ("position", models.CharField(max_length=50, verbose_name="Position")),
                ("text", models.TextField(verbose_name="Text")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="testmonials", verbose_name="Image"
                    ),
                ),
            ],
            options={
                "verbose_name": "Testmonial",
                "verbose_name_plural": "Testmonials",
            },
        ),
    ]
