# Generated by Django 5.1.4 on 2025-04-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_alter_testmonial_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testmonial",
            name="image",
            field=models.ImageField(
                blank=True,
                default="testmonials/default.png",
                upload_to="testmonials/",
                verbose_name="Image",
            ),
        ),
    ]
