# Generated by Django 5.1.2 on 2025-04-11 18:05

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_alter_testmonial_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="img",
            field=models.ImageField(
                upload_to=main.models.path_and_rename, verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="testmonial",
            name="image",
            field=models.ImageField(
                blank=True,
                default="default.png",
                upload_to="testmonials/",
                verbose_name="Image",
            ),
        ),
    ]
