# Generated by Django 5.1.2 on 2025-04-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_alter_service_img_alter_testmonial_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="paragraph_1",
            field=models.TextField(
                default="fghjkhgcvhbjnk", verbose_name="Main Paragragh"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="paragraph_2",
            field=models.TextField(
                default="xfcgvhjbknlm;,", verbose_name="Sub Paragragh"
            ),
            preserve_default=False,
        ),
    ]
