# Generated by Django 5.1.2 on 2025-04-11 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_project_paragraph_1_project_paragraph_2"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="projects/images/", verbose_name="Image"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="main.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "ProjectImage",
                "verbose_name_plural": "ProjectImages",
            },
        ),
    ]
