# Generated by Django 5.1.2 on 2025-04-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_projectimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectimage",
            options={
                "verbose_name": "Project_Image",
                "verbose_name_plural": "Project_Images",
            },
        ),
        migrations.RemoveField(
            model_name="project",
            name="excerpt",
        ),
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(to="main.tag", verbose_name="tags"),
        ),
    ]
