# Generated by Django 5.1.2 on 2025-04-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_alter_projectimage_options_remove_project_excerpt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="contacted",
            field=models.BooleanField(default=False, verbose_name="Contacted yet"),
        ),
    ]
