# Generated by Django 5.1.2 on 2025-04-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_newsletter_contacted"),
    ]

    operations = [
        migrations.CreateModel(
            name="contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                ("phone", models.CharField(max_length=50, verbose_name="Phone Number")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("subject", models.CharField(max_length=50, verbose_name="Subject")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Date"
                    ),
                ),
                (
                    "contacted",
                    models.BooleanField(default=False, verbose_name="Contacted yet"),
                ),
            ],
            options={
                "verbose_name": "contact",
                "verbose_name_plural": "contacts",
            },
        ),
        migrations.DeleteModel(
            name="newsletter",
        ),
    ]
